version: "2.9"
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  web:
    build: ./web
    hostname: web
    ports:
      - '81:5000'
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - web